name: steel_budy
description: "A new Steel Budy project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  firebase_messaging: ^15.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
